import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + String(e.stack || e)));
page.on('console', (m) => errors.push(m.type() + ': ' + m.text()));
await page.goto('http://localhost:5179/', { waitUntil: 'networkidle' });
await page.getByTitle(/Live Edit/).click();
await page.waitForTimeout(300);
await page.keyboard.press('p');
await page.waitForTimeout(150);
await page.mouse.click(700, 400);
await page.waitForTimeout(150);
await page.mouse.click(700, 550);
await page.waitForTimeout(150);
await page.mouse.dblclick(950, 550);
await page.waitForTimeout(400);
console.log('=== log ===');
console.log(errors.join('\n'));
await browser.close();
