import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:5179/', { waitUntil: 'networkidle' });
await page.getByTitle(/Live Edit/).click();
await page.waitForTimeout(300);
await page.keyboard.press('p');
await page.waitForTimeout(150);
await page.mouse.click(700, 400);
await page.waitForTimeout(200);
const stillArmed1 = await page.getByTitle(/Draw new polygon/).evaluate(el => getComputedStyle(el).background);
console.log('pen button bg after point1:', stillArmed1);
await page.mouse.move(700, 550);
await page.waitForTimeout(100);
await page.mouse.down();
await page.waitForTimeout(50);
await page.mouse.up();
await page.waitForTimeout(200);
const stillArmed2 = await page.getByTitle(/Draw new polygon/).evaluate(el => getComputedStyle(el).background);
console.log('pen button bg after point2 mousedown/up:', stillArmed2);
await page.screenshot({ path: '/tmp/step2b.png', clip: { x: 600, y: 300, width: 450, height: 350 } });
await browser.close();
