import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:5179/', { waitUntil: 'networkidle' });
await page.getByTitle(/Live Edit/).click();
await page.waitForTimeout(300);
await page.keyboard.press('p');
await page.waitForTimeout(150);
await page.mouse.click(700, 400);
await page.waitForTimeout(200);
await page.screenshot({ path: '/tmp/step1.png', clip: { x: 600, y: 300, width: 450, height: 350 } });
await page.mouse.click(700, 550);
await page.waitForTimeout(200);
await page.screenshot({ path: '/tmp/step2.png', clip: { x: 600, y: 300, width: 450, height: 350 } });
await page.mouse.click(950, 550);
await page.waitForTimeout(200);
await page.screenshot({ path: '/tmp/step3.png', clip: { x: 600, y: 300, width: 450, height: 350 } });
await page.mouse.dblclick(950, 550);
await page.waitForTimeout(300);
await page.screenshot({ path: '/tmp/step4.png', clip: { x: 600, y: 300, width: 450, height: 350 } });
await browser.close();
