import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:5179/', { waitUntil: 'networkidle' });
await page.getByTitle(/Live Edit/).click();
await page.waitForTimeout(300);
await page.keyboard.press('p');
await page.waitForTimeout(150);
await page.mouse.click(700, 400);
await page.waitForTimeout(200);
await page.mouse.click(700, 550);
await page.waitForTimeout(200);
await page.screenshot({ path: '/tmp/full-after2.png' });
await browser.close();
